# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tone_datagen',
                'doc_host': 'https://leoauri.github.io',
                'git_url': 'https://github.com/leoauri/tone_datagen',
                'lib_path': 'tone_datagen'},
  'syms': { 'tone_datagen.core': {'tone_datagen.core.foo': ('core.html#foo', 'tone_datagen/core.py')},
            'tone_datagen.tone_element': {'tone_datagen.tone_element.tone': ('tone_element.html#tone', 'tone_datagen/tone_element.py')}}}
