# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_mix.ipynb.

# %% auto 0
__all__ = ['normalised', 'mixed_tones', 'resize_array', 'generate']

# %% ../nbs/02_mix.ipynb 2
from .tonegen import RandomToneGen, gamma, uniform, normal, clip, quant
from audiolazy import Streamix, sHz, zeros, ones, line, Stream
from pedalboard import Pedalboard, Reverb
from fastcore.script import call_parse

# %% ../nbs/02_mix.ipynb 9
import numpy as np

# %% ../nbs/02_mix.ipynb 20
def normalised(stream):
    mix = np.array(list(stream))
    max_abs = np.max(np.abs(mix))
    if max_abs > 1:
        mix /= max_abs

    return mix

# %% ../nbs/02_mix.ipynb 22
def mixed_tones(rate=44100, longerness=1):
    s, Hz = sHz(rate)
    tonegen = RandomToneGen(
        gamma(3) * 100 + 20,
        gamma(2) * -2 - 2,
        (uniform(0, 1.5) + clip(gamma(0.9) * 0.2, high=4)) * longerness,
        uniform(0.05, 0.6),
        uniform() * 1.5,
        uniform(0.05, 1)
    )
    reverb = Pedalboard([Reverb(wet_level=1, dry_level=0.2, room_size=0.75)])
    
    smix = Streamix()
    for _ in range(quant((normal() * 0.8 + 2.7) * longerness, range(1, int(6 * longerness)))()):
        smix.add(0, tonegen())
    env = Stream(ones(len(list(smix.copy())) + s), line(s, 1, 0))
    # make stream as long as envelope
    smix.append(zeros(s * 2))

    mix = normalised(smix)
    return normalised(env * reverb(mix, rate))

# %% ../nbs/02_mix.ipynb 24
def resize_array(arr, desired_length):
    arr = np.asarray(arr)
    current_length = arr.shape[0]
    
    if current_length > desired_length:
        # Truncate
        return arr[:desired_length]
    elif current_length < desired_length:
        # Pad with zeros
        return np.pad(arr, (0, desired_length - current_length), 'constant')
    else:
        # Already the correct length
        return arr

# %% ../nbs/02_mix.ipynb 26
from scipy.io.wavfile import write as wavwrite
from pathlib import Path

# %% ../nbs/02_mix.ipynb 29
@call_parse
def generate(outdir:str=None, n_generate:int=30, longerness:float=1, sample_len:int=2**18, rate:int=44100):
    if outdir is None:
        raise ValueError("outdir must be specified.")
    outdir = Path(outdir)
    outdir.mkdir(parents=True, exist_ok=True)
    try:
        fnum = max(int(p.stem) for p in outdir.iterdir() if p.is_file() and p.stem.isdigit())
    except ValueError:
        fnum = -1

    for _ in range(n_generate):
        samp = mixed_tones(longerness=longerness, rate=rate)
        # Has to be a power of two or the model output shape mismatches sample shape
        samp = resize_array(samp, sample_len)

        fnum += 1
        fname = str(outdir / f"{fnum:06d}.wav")

        wavwrite(fname, rate, samp)
        print(f"Wrote {fname}")
