# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_randomise.ipynb.

# %% auto 0
__all__ = ['RandomToneGen', 'Distribution', 'ScipyDist', 'Add', 'Mul', 'Negate', 'Constant', 'Clip', 'Quantise', 'normal',
           'gamma', 'uniform', 'clip', 'quant']

# %% ../nbs/01_randomise.ipynb 2
from .tone_element import tone

# %% ../nbs/01_randomise.ipynb 6
class RandomToneGen:
    def __init__(self, freq_dist, db_dist, delay_dist, attack_dist, sustain_dist, release_dist):
        self.freq_dist = freq_dist
        self.db_dist = db_dist
        self.delay_dist = delay_dist
        self.attack_dist = attack_dist
        self.sustain_dist = sustain_dist
        self.release_dist = release_dist

    def __call__(self):
        return tone(
            self.freq_dist(),
            self.db_dist(),
            self.delay_dist(),
            self.attack_dist(),
            self.sustain_dist(),
            self.release_dist()
        )

# %% ../nbs/01_randomise.ipynb 10
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm, gamma as sp_gamma, uniform as sp_uniform

class Distribution:
    def __call__(self):
        raise NotImplementedError
    
    def pdf(self, xs=None, n=10000):
        samples = [self() for _ in range(n)]
        xs = xs or np.linspace(min(samples), max(samples), 200)
        density, bins = np.histogram(samples, bins=xs, density=True)
        plt.plot(bins[:-1], density)
        plt.show()

    def __add__(self, other):
        return Add(self, other)

    def __sub__(self, other):
        other = other if isinstance(other, Distribution) else Constant(other)
        return Add(self, Negate(other))

    def __rsub__(self, other):
        other = other if isinstance(other, Distribution) else Constant(other)
        return Add(other, Negate(self))
    
    def __mul__(self, other):
        return Mul(self, other)

class ScipyDist(Distribution):
    def __init__(self, dist_fn, *args, **kwargs):
        self.dist = dist_fn(*args, **kwargs)

    def __call__(self):
        return self.dist.rvs()

class Add(Distribution):
    def __init__(self, a, b):
        self.a = a if isinstance(a, Distribution) else Constant(a)
        self.b = b if isinstance(b, Distribution) else Constant(b)

    def __call__(self):
        return self.a() + self.b()

class Mul(Distribution):
    def __init__(self, a, b):
        self.a = a if isinstance(a, Distribution) else Constant(a)
        self.b = b if isinstance(b, Distribution) else Constant(b)

    def __call__(self):
        return self.a() * self.b()
    
class Negate(Distribution):
    def __init__(self, dist):
        self.dist = dist if isinstance(dist, Distribution) else Constant(dist)

    def __call__(self):
        return -self.dist()

class Constant(Distribution):
    def __init__(self, value):
        self.value = value

    def __call__(self):
        return self.value

class Clip(Distribution):
    def __init__(self, dist, *, low=None, high=None):
        self.dist = dist if isinstance(dist, Distribution) else Constant(dist)
        self.low = low
        self.high = high

    def __call__(self):
        val = self.dist()
        if self.low is not None:
            val = max(self.low, val)
        if self.high is not None:
            val = min(self.high, val)
        return val

class Quantise(Distribution):
    def __init__(self, dist, levels):
        self.dist = dist
        self.levels = np.array(list(levels))

    def __call__(self):
        val = self.dist()
        return self.levels[np.abs(self.levels - val).argmin()]

# Aliases
def normal(mu=0, sigma=1): return ScipyDist(norm, mu, sigma)
def gamma(alpha, scale=1): return ScipyDist(sp_gamma, alpha, scale=scale)
def uniform(low=0, high=1): return ScipyDist(sp_uniform, loc=low, scale=high - low)

def clip(d, *, low=None, high=None):
    return Clip(d, low=low, high=high)

def quant(d, levels): return Quantise(d, levels)
