# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_tone_element.ipynb.

# %% auto 0
__all__ = ['db2amp', 'tone']

# %% ../nbs/00_tone_element.ipynb 3
from audiolazy import Stream, sinusoid, sHz, line, zeros, ones

# %% ../nbs/00_tone_element.ipynb 6
db2amp = lambda db: 10 ** (db / 20)

# %% ../nbs/00_tone_element.ipynb 12
def tone(freq, db, delay, attack, sustain, release, rate=44100):
    s, Hz = sHz(rate)
    sine = sinusoid(freq * Hz) * db2amp(db)
    envelope = Stream(zeros(s * delay), line(s * attack, 0, 1), ones(s * sustain), line(s * release, 1, 0))
    return envelope * sine
