# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/util.ipynb.

# %% auto 0
__all__ = ['see', 'hear']

# %% ../nbs/util.ipynb 2
from matplotlib import pyplot as plt

# %% ../nbs/util.ipynb 3
def see(stream):
    plt.plot(list(stream.copy()))
    plt.show()

# %% ../nbs/util.ipynb 6
from IPython.display import Audio, display

# %% ../nbs/util.ipynb 7
def hear(stream):
    display(Audio(list(stream.copy()), rate=44100))
